@port=3000
@host=http://localhost:{{port}}/api/
@authhost={{host}}
@patienthost={{host}}patient
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDRmNjVhMDNmMGM5ODFjNDgwYTI2NGIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTY5MDYxOTQsImV4cCI6MTYxNjk5MjU5NH0.a79Gz6xU1m4XEW_8nAV4mWfkUTyZGlAnbkpz437vGUg
@id=605492c27091fa1c7cd4a2bd

###
# login
POST {{authhost}}login HTTP/1.1
content-type : application/json

{
    "username":"17bmiit107@gmail.com",
    "password":"admin"
}

###
# add staffmember
POST {{patienthost}}/add HTTP/1.1
x-access-token : {{token}}

{
    "name":"Kachhadiya Kishan Sanjaybhai",
    "contactno":"7069993960",
    "username":"17bmiit107@gmail.com",
    "password":"admin",
    "role":"admin",
}

###
# get list of staffmember with pagination
GET {{patienthost}}/list HTTP/1.1
x-access-token : {{token}}

###
# get staffmember details by id
PUT {{patienthost}}/get/{{id}} HTTP/1.1
x-access-token : {{token}}

###
#update staffmember details by id
PATCH  {{patienthost}}/update/{{id}} HTTP/1.1
x-access-token : {{token}}

{
    "name":"Kachhadiya Kishan Sanjaybhai",
    "contactno":"7069993960",
    "username":"17bmiit107@gmail.com",
    "password":"admin",
    "role":"admin",
}

###
# deactivate staffmember with id
POST {{patienthost}}/deactivate/{{id}} HTTP/1.1
x-access-token : {{token}}

###
# activate staffmember with id
POST {{patienthost}}/activate/{{id}} HTTP/1.1
x-access-token : {{token}}

###
# delete staffmember with id
DELETE {{patienthost}}/delete/{{id}} HTTP/1.1
x-access-token : {{token}}

